// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Para migrations, use a URL direta (porta 5432)
    // Para queries normais, o PrismaClient usará DATABASE_URL (porta 6543)
    url: process.env['DATABASE_URL'],
  },
});
